// main.js
console.log("Hello World")
console.log("Guten Tag Welt")
console.log("Hola Mundo")
console.log("Bonjour Monde")
console.log("你好世界")
console.log("こんにちは世界")
console.log("안녕하세요 세계")
console.log("Привет мир")
console.log("Ciao Mondo")
console.log("Olá Mundo")
console.log("Hallo Welt")
console.log("Hej Världen")
console.log("Salut Monde")
console.log("Zdravo Svijete")
console.log("Merhaba Dünya")
console.log("Salam Dunya")
console.log("Shalom Olam")
console.log("Halo Dunia")
console.log("Ahoj světe")
console.log("Konnichiwa Sekai")
console.log("Namaste Duniya")
console.log("Hei Maailma")
console.log("Tere Huvalepa")
